### ISSUE TITLE
build in Ubuntu 16.04

### ISSUE THREAD

**Issue by Thanh-Binh** [yandex/faster-rnnlm#28]
hi,
after call ./build.sh I have got the errors
In file included from ../faster-rnnlm/nce.h:12:0,
                 from nce.cc:1:
../faster-rnnlm/util.h:29:100: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
 inline void Dump(const Eigen::Matrix<Real, rows, Eigen::Dynamic, Eigen::RowMajor>& matrix, FILE* fo) {
                                                                                                    ^
../faster-rnnlm/util.h:35:114: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
 inline void Load(Eigen::Matrix<Real, rows, Eigen::Dynamic, Eigen::RowMajor, _MaxRows, _MaxCols>* matrix, FILE* fo) {

Could you pls help me?
Thanks

**Comment by Thanh-Binh** [comment]
I solved this problem today, if I use a version before adapting for VS2015.
